name: PR Compliance

on: 
  pull_request_target:
    types: [opened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const files = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            if(files.includes("lib/layouts") || files.includes("build")){
              throw "Changes to protected locations not allowed."
            }
            console.log(files)
            
      - name: Comment PR
        if: success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :wave: Hello @${{ github.actor }}! Please make sure to review the [Contributing Guidelines](https://github.com/simple-keyboard/simple-keyboard-layouts/blob/master/CONTRIBUTING.md) to ensure your PR is compliant. Thank you!
          reactions: eyes
          comment_tag: compliance

      - name: Reject PR
        if: failure()
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{github.event.number}}
          comment: "Thank you for contribution, but we are no longer accepting changes to the `lib/layouts` or `build` directories. Please file an issue if you find a bug in the existing layouts."
          delete-branch: true
          
      
